# Generated by Django 5.0.1 on 2024-02-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_category_remove_book_price_book_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload the author image', upload_to='authors/'),
        ),
    ]
